<?php
function my_register_fields(){
	include_once get_template_directory() . '/inc/acf-repeater/repeater.php';
}
add_action('acf/register_fields', 'my_register_fields');
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_options',
		'title' => 'Home - Destaque - Superiores',
		'fields' => array (
			array (
				'key' => 'field_54c38279b37e8',
				'label' => __('Destaque 1','odin'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54c38286b37e9',
				'label' => 'Título destaque 1',
				'name' => 'titulo_destaque_1',
				'type' => 'text',
				'instructions' => 'Adicione o título para o primeiro destaque do cabeçalho da Home.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c386e4b37ea',
				'label' => 'Sub Título destaque 1',
				'name' => 'sub_titulo_destaque_1',
				'type' => 'text',
				'instructions' => 'Adicione o sub título para o primeiro destaque do cabeçalho da Home.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c3870eb37eb',
				'label' => 'Link destaque 1',
				'name' => 'link_destaque_1',
				'type' => 'text',
				'instructions' => 'Adicione o link (URL) para o primeiro destaque do cabeçalho da Home. Caso deixe em branco ele aparecerá apenas como um banner informativo.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c3873eb37ec',
				'label' => 'Background destaque 1',
				'name' => 'background_destaque_1',
				'type' => 'image',
				'instructions' => 'Adicione uma imagem para o background do primeiro destaque do cabeçalho da Home.',
				'required' => 1,
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_54c3827944b37e8',
				'label' => __('Destaque 2','odin'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54c397bda7029',
				'label' => 'Título destaque 2',
				'name' => 'titulo_destaque_2',
				'type' => 'text',
				'instructions' => 'Adicione o título para o segundo destaque do cabeçalho da Home.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c397df7d211',
				'label' => 'Sub Título destaque 2',
				'name' => 'sub_titulo_destaque_2',
				'type' => 'text',
				'instructions' => 'Adicione o sub título para o segundo destaque do cabeçalho da Home.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c397ef7d212',
				'label' => 'Link destaque 2',
				'name' => 'link_destaque_2',
				'type' => 'text',
				'instructions' => 'Adicione o link (URL) para o segundo destaque do cabeçalho da Home. Caso deixe em branco ele aparecerá apenas como um banner informativo.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c397fc7d213',
				'label' => 'Background destaque 2',
				'name' => 'background_destaque_2',
				'type' => 'image',
				'instructions' => 'Adicione uma imagem para o background do segundo destaque do cabeçalho da Home.',
				'required' => 1,
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_rodape',
		'title' => 'Rodapé',
		'fields' => array (
			array (
				'key' => 'field_54de093924e7c',
				'label' => 'Endereço',
				'name' => 'endereço',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'link_pessoa_fisica',
				'label' => __('Como Apoiar - Link Pessoa fisica','odin'),
				'name' => 'link_pessoa_fisica',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'link_pessoa_juridica',
				'label' => __('Como Apoiar - Link Pessoa juridica','odin'),
				'name' => 'link_pessoa_juridica',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54de0ecd9c1f7',
				'label' => 'Link Artesol + Iguatemi',
				'name' => 'parceiro-iguatemi',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54de12109b2b9',
				'label' => 'Link Todos os Parceiros',
				'name' => 'todos-parceiros',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54de3d1d58b73',
				'label' => 'Link Imprensa',
				'name' => 'link-imprensa',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54de3dbb58b74',
				'label' => 'Link Download Release',
				'name' => 'link-release',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54de44fbf4813',
				'label' => 'Social',
				'name' => 'social_repeater',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54de451cf4814',
						'label' => 'Nome da rede social',
						'name' => 'social_repeater_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_54de4535f4815',
						'label' => 'Link',
						'name' => 'social_repeater_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_slider-home',
		'title' => 'Slider home',
		'fields' => array (
			array (
				'key' => 'field_54d8be6f23184',
				'label' => 'Deseja exibir essa página no slider da página inicial?',
				'name' => 'slider_home',
				'type' => 'radio',
				'choices' => array (
					'true' => 'Sim',
					'false' => 'Não',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'false',
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '!=',
					'value' => 'brasa_slider_cpt',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_home',
		'title' => __('Home - Widgets','odin'),
		'fields' => array (
			array (
				'key' => 'field_54ff1ac1a6fbe',
				'label' => 'Box de informações',
				'name' => 'box_home_repeater',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54ff2451a6fbf',
						'label' => 'Titulo',
						'name' => 'box_home_repeater_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_54ff251ba6fc1',
						'label' => 'Texto',
						'name' => 'box_home_repeater_text',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_54ff247ca6fc0',
						'label' => 'Classe do icone',
						'name' => 'box_home_repeater_icon',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'servicos' => 'Marrom',
							'agenda' => 'Azul',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'servicos',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_54ff27a896406',
						'label' => 'Classe do botão',
						'name' => 'box_home_repeater_btn',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'bg-marrom-artesol' => 'Marrom',
							'bg-azul-artesol' => 'Azul',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'bg-marrom-artesol',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_54ff27ec96407',
						'label' => 'Texto do botão',
						'name' => 'box_home_repeater_btn_text',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_54ff293928f57',
						'label' => 'Link',
						'name' => 'box_home_repeater_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => 2,
				'layout' => 'row',
				'button_label' => 'Adicionar novo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
/*if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_home-widgets-projetos-rede',
		'title' => 'Home - Widgets',
		'fields' => array (
			array (
				'key' => 'field_551060b9c0832',
				'label' => '',
				'name' => 'box_projetos',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_551060b9c0833',
						'label' => 'Titulo',
						'name' => 'box_home_repeater_title',
						'type' => 'text',
						'instructions' => 'Deixe vazio para não exibir',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_551060b9c0834',
						'label' => 'Texto',
						'name' => 'box_home_repeater_text',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_551060b9c0835',
						'label' => 'Classe do Box',
						'name' => 'box_home_repeater_class',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'aceleracao' => 'Rede',
							'projetos' => 'Projetos',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'aceleracao',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_551060b9c0838',
						'label' => 'Link',
						'name' => 'box_home_repeater_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_box_home_repeater_bg',
						'label' => 'Imagem do Background (Deixe vazio para usar o padrão)',
						'name' => 'box_home_repeater_bg',
						'type' => 'image',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_box_home_repeater_icon',
						'label' => 'Icone (Deixe vazio para usar o padrão)',
						'name' => 'box_home_repeater_icon',
						'type' => 'image',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => 2,
				'layout' => 'row',
				'button_label' => 'Adicionar novo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
/*if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_institucional-widgets-projetos-rede',
		'title' => 'Page Institucional - Widgets - Projetos & Rede',
		'fields' => array (
			array (
				'key' => 'box_projetos_institucional',
				'label' => '',
				'name' => 'box_projetos_institucional',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'box_institucional_repeater_title',
						'label' => 'Titulo',
						'name' => 'box_home_repeater_title',
						'type' => 'text',
						'instructions' => 'Deixe vazio para não exibir',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'box_institucionalfield_551060b9c0834',
						'label' => 'Texto',
						'name' => 'box_home_repeater_text',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'box_institucionalfield_551060b9c0835',
						'label' => 'Classe do Box',
						'name' => 'box_home_repeater_class',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'aceleracao' => 'Rede',
							'projetos' => 'Projetos',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'aceleracao',
						'layout' => 'vertical',
					),
					array (
						'key' => 'box_institucionalfield_551060b9c0838',
						'label' => 'Link',
						'name' => 'box_home_repeater_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => 1,
				'layout' => 'row',
				'button_label' => 'Adicionar novo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
*/
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_home-destaques',
		'title' => 'Home - Destaques - Inferiores',
		'fields' => array (
			array (
				'key' => 'field_551bf1312785dwdwc',
				'label' => 'Destaque 1',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_551bf1402785d',
				'label' => 'Título - 1',
				'name' => 'home_feature_1_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_551bf1582785e',
				'label' => 'Descrição - 1',
				'name' => 'home_feature_1_resume',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_551bf1802785f',
				'label' => 'Link - 1 ',
				'name' => 'home_feature_1_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_551bf19b27860',
				'label' => 'Imagem de background - 1',
				'name' => 'home_feature_1_bg',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_551bf1af27861',
				'label' => 'Imagem de ícone - 1',
				'name' => 'home_feature_1_icon',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_551bf495543db',
				'label' => 'Classe do box - 1',
				'name' => 'home_feature_1_class',
				'type' => 'radio',
				'choices' => array (
					'aceleracao' => 'Rede',
					'projetos' => 'Projetos',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_551fkfk2785dwdwc',
				'label' => 'Destaque 2',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_551bf14001929922785d',
				'label' => 'Título - 2',
				'name' => 'home_feature_2_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_551bfs27754355e',
				'label' => 'Descrição - 2',
				'name' => 'home_feature_2_resume',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_55bf18begafffff',
				'label' => 'Link - 2 ',
				'name' => 'home_feature_2_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_551bfllaajd12260',
				'label' => 'Imagem de background - 2',
				'name' => 'home_feature_2_bg',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_fsfsBNbf1af27861',
				'label' => 'Imagem de ícone - 2',
				'name' => 'home_feature_2_icon',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_51231bfnhhd543db',
				'label' => 'Classe do box - 2',
				'name' => 'home_feature_2_class',
				'type' => 'radio',
				'choices' => array (
					'aceleracao' => 'Rede',
					'projetos' => 'Projetos',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_29752fd9292785c',
				'label' => 'Destaque 3',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_feature_3_title',
				'label' => 'Título - 3',
				'name' => 'home_feature_3_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_home_feature_3_resume',
				'label' => 'Descrição - 3',
				'name' => 'home_feature_3_resume',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_home_feature_3_link',
				'label' => 'Link - 3 ',
				'name' => 'home_feature_3_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_home_feature_3_bg',
				'label' => 'Imagem de background - 3',
				'name' => 'home_feature_3_bg',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_home_feature_3_icon',
				'label' => 'Imagem de ícone - 3',
				'name' => 'home_feature_3_icon',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_home_feature_3_class',
				'label' => 'Classe do box - 3',
				'name' => 'home_feature_3_class',
				'type' => 'radio',
				'choices' => array (
					'aceleracao' => 'Rede',
					'projetos' => 'Projetos',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_551bgkgkg2785dwdwc',
				'label' => 'Destaque 4',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_home_feature_4_title',
				'label' => 'Título - 4',
				'name' => 'home_feature_4_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_home_feature_4_resume',
				'label' => 'Descrição - 4',
				'name' => 'home_feature_4_resume',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_home_feature_4_link',
				'label' => 'Link - 4 ',
				'name' => 'home_feature_4_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_home_feature_4_bg',
				'label' => 'Imagem de background - 4',
				'name' => 'home_feature_4_bg',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_home_feature_4_icon',
				'label' => 'Imagem de ícone - 4',
				'name' => 'home_feature_4_icon',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_home_feature_4_class',
				'label' => 'Classe do box - 4',
				'name' => 'home_feature_4_class',
				'type' => 'radio',
				'choices' => array (
					'aceleracao' => 'Rede',
					'projetos' => 'Projetos',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),

		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 2,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_projetos',
		'title' => 'Projetos',
		'fields' => array (
			array (
				'key' => 'field_552055dade941',
				'label' => 'Ano',
				'name' => 'project_year',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_552055f0de942',
				'label' => 'Localização',
				'name' => 'project_local',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5520560ede943',
				'label' => 'Duração',
				'name' => 'project_time',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55205630de944',
				'label' => 'Artesão beneficiados',
				'name' => 'project_beneficiados',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_55205642de945',
				'label' => 'Genero',
				'name' => 'project_type',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5520566dde946',
				'label' => 'Parceiro financiador',
				'name' => 'project_repeater',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_55205695de947',
						'label' => 'Imagem do financiador',
						'name' => 'project_repeater_img',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_552056c4de948',
						'label' => 'Link',
						'name' => 'project_repeater_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'projetos',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_informacoes-da-tipologia',
		'title' => 'Informações da tipologia',
		'fields' => array (
			array (
				'key' => 'field_5524306676fd7',
				'label' => 'Imagem destacada',
				'name' => 'tipo_thumb',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'tipos',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_rede-conheca',
		'title' => 'Rede - Conheça',
		'fields' => array (
			array (
				'key' => 'field_55242654be954',
				'label' => 'Texto do botão Conheça a Rede',
				'name' => 'conheca_btn_txt',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55242687be955',
				'label' => 'Link do botão Conheça a Rede',
				'name' => 'conheca_btn',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-rede.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_rede-participe',
		'title' => 'Rede - Participe',
		'fields' => array (
			array (
				'key' => 'field_552441788a0d1',
				'label' => 'Links',
				'name' => 'rede_participe_repeater',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_552442c36e155',
						'label' => 'Texto do Link',
						'name' => 'text',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_552442608a0d2',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => 4,
				'layout' => 'table',
				'button_label' => 'Adicionar Link',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-rede.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_rede-destaques',
		'title' => 'Rede - Destaques',
		'fields' => array (
			array (
				'key' => 'field_54c38279b37e8',
				'label' => __('Destaque 1','odin'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54c38286b37e9',
				'label' => 'Título destaque 1',
				'name' => 'titulo_destaque_1',
				'type' => 'text',
				'instructions' => 'Adicione o título para o primeiro destaque do cabeçalho da Rede.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c386e4b37ea',
				'label' => 'Sub Título destaque 1',
				'name' => 'sub_titulo_destaque_1',
				'type' => 'text',
				'instructions' => 'Adicione o sub título para o primeiro destaque do cabeçalho da Rede.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c3870eb37eb',
				'label' => 'Link destaque 1',
				'name' => 'link_destaque_1',
				'type' => 'text',
				'instructions' => 'Adicione o link (URL) para o primeiro destaque do cabeçalho da Rede. Caso deixe em branco ele aparecerá apenas como um banner informativo.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c3873eb37ec',
				'label' => 'Background destaque 1',
				'name' => 'background_destaque_1',
				'type' => 'image',
				'instructions' => 'Adicione uma imagem para o background do primeiro destaque do cabeçalho da Rede.',
				'required' => 1,
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_54c3827944b37e8',
				'label' => __('Destaque 2','odin'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54c397bda7029',
				'label' => 'Título destaque 2',
				'name' => 'titulo_destaque_2',
				'type' => 'text',
				'instructions' => 'Adicione o título para o segundo destaque do cabeçalho da Rede.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c397df7d211',
				'label' => 'Sub Título destaque 2',
				'name' => 'sub_titulo_destaque_2',
				'type' => 'text',
				'instructions' => 'Adicione o sub título para o segundo destaque do cabeçalho da Rede.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c397ef7d212',
				'label' => 'Link destaque 2',
				'name' => 'link_destaque_2',
				'type' => 'text',
				'instructions' => 'Adicione o link (URL) para o segundo destaque do cabeçalho da Rede. Caso deixe em branco ele aparecerá apenas como um banner informativo.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c397fc7d213',
				'label' => 'Background destaque 2',
				'name' => 'background_destaque_2',
				'type' => 'image',
				'instructions' => 'Adicione uma imagem para o background do segundo destaque do cabeçalho da Rede.',
				'required' => 1,
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
				array (
				'key' => 'field_5sec3827944b37e8',
				'label' => __('Destaque 3','odin'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_a54c397bdae7029',
				'label' => 'Título destaque 3',
				'name' => 'titulo_destaque_3',
				'type' => 'text',
				'instructions' => 'Adicione o título para o terceiro destaque do cabeçalho da Rede.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c397df7fnade11',
				'label' => 'Sub Título destaque 3',
				'name' => 'sub_titulo_destaque_3',
				'type' => 'text',
				'instructions' => 'Adicione o sub título para o terceiro destaque do cabeçalho da Rede.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c3ffa97ef7d212',
				'label' => 'Link destaque 3',
				'name' => 'link_destaque_3',
				'type' => 'text',
				'instructions' => 'Adicione o link (URL) para o terceiro destaque do cabeçalho da Rede. Caso deixe em branco ele aparecerá apenas como um banner informativo.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54c397fc7fd21ee3',
				'label' => 'Background destaque 3',
				'name' => 'background_destaque_3',
				'type' => 'image',
				'instructions' => 'Adicione uma imagem para o background do terceiro destaque do cabeçalho da Rede.',
				'required' => 1,
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),

		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-rede.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_projetos-2',
		'title' => 'Projetos',
		'fields' => array (
			array (
				'key' => 'field_55258a78c5b74',
				'label' => 'Descrição do tipo de post Projetos',
				'name' => 'project_content',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_publicacoes',
		'title' => 'Publicações',
		'fields' => array (
			array (
				'key' => 'field_Yellowrrrr3r358a78c5b74',
				'label' => 'Descrição do tipo de post Publicações',
				'name' => 'publicacao_content',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
if(function_exists("register_field_group"))
{
	$id = get_category_by_slug('agenda');
	$id = $id->term_id;
	register_field_group(array (
		'id' => 'acf_agenda',
		'title' => 'Agenda',
		'fields' => array (
			array (
				'key' => 'field_5540dd8489ee9',
				'label' => 'Data do evento',
				'name' => 'evento_data',
				'type' => 'date_picker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5540ddc989eea',
				'label' => 'Horario',
				'name' => 'evento_hora',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5540ddd689eeb',
				'label' => 'Localização',
				'name' => 'evento_local',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_category',
					'operator' => '==',
					'value' => $id,
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
